/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness probe (process is up)
     * @description Always 200 while the process can serve requests. Used by orchestrators to decide restarts; does not check dependencies.
     */
    get: operations['liveness'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/readyz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness probe (Redis reachable)
     * @description 200 while Redis answers PING within 1s, 503 otherwise. Used by load balancers to stop routing to an instance that lost its datastore.
     */
    get: operations['readiness'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a new login
     * @description Creates a user with a unique (case-insensitive) username. Uniqueness is enforced atomically in Redis (SET NX) — concurrent duplicate registrations cannot race.
     */
    post: operations['createUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify a username/password pair
     * @description Returns 200 when the credentials are valid and 401 otherwise. Unknown-username and wrong-password failures are indistinguishable by response AND by timing (dummy Argon2id verification). Failed attempts are rate limited per username; the counter clears on success.
     */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  liveness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ok';
          };
        };
      };
    };
  };
  readiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ready';
          };
        };
      };
      /** @description RFC 9457 Problem Details */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description URI reference identifying the problem type */
            type: string;
            /** @description Short human-readable summary of the problem type */
            title: string;
            /** @description HTTP status code */
            status: number;
            /** @description Stable machine-readable problem code */
            code: string;
            /** @description Occurrence-specific explanation */
            detail?: string;
            /** @description URI of the request that failed */
            instance?: string;
            /** @description Correlation id (X-Request-Id) */
            requestId?: string;
            /** @description Field-level validation failures */
            errors?: {
              field: string;
              rule: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  createUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description 3-32 chars; letters, digits, ".", "_", "-". Case-insensitively unique. */
          username: string;
          /** @description Checked against the password policy (NIST SP 800-63B-4): length + common-password blocklist; no composition rules. */
          password: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: {
              username: string;
              /** @description RFC 3339 UTC timestamp */
              createdAt: string;
            };
          };
        };
      };
      /** @description RFC 9457 Problem Details */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description URI reference identifying the problem type */
            type: string;
            /** @description Short human-readable summary of the problem type */
            title: string;
            /** @description HTTP status code */
            status: number;
            /** @description Stable machine-readable problem code */
            code: string;
            /** @description Occurrence-specific explanation */
            detail?: string;
            /** @description URI of the request that failed */
            instance?: string;
            /** @description Correlation id (X-Request-Id) */
            requestId?: string;
            /** @description Field-level validation failures */
            errors?: {
              field: string;
              rule: string;
              message: string;
            }[];
          };
        };
      };
      /** @description RFC 9457 Problem Details */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description URI reference identifying the problem type */
            type: string;
            /** @description Short human-readable summary of the problem type */
            title: string;
            /** @description HTTP status code */
            status: number;
            /** @description Stable machine-readable problem code */
            code: string;
            /** @description Occurrence-specific explanation */
            detail?: string;
            /** @description URI of the request that failed */
            instance?: string;
            /** @description Correlation id (X-Request-Id) */
            requestId?: string;
            /** @description Field-level validation failures */
            errors?: {
              field: string;
              rule: string;
              message: string;
            }[];
          };
        };
      };
      /** @description RFC 9457 Problem Details */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description URI reference identifying the problem type */
            type: string;
            /** @description Short human-readable summary of the problem type */
            title: string;
            /** @description HTTP status code */
            status: number;
            /** @description Stable machine-readable problem code */
            code: string;
            /** @description Occurrence-specific explanation */
            detail?: string;
            /** @description URI of the request that failed */
            instance?: string;
            /** @description Correlation id (X-Request-Id) */
            requestId?: string;
            /** @description Field-level validation failures */
            errors?: {
              field: string;
              rule: string;
              message: string;
            }[];
          };
        };
      };
      /** @description RFC 9457 Problem Details */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description URI reference identifying the problem type */
            type: string;
            /** @description Short human-readable summary of the problem type */
            title: string;
            /** @description HTTP status code */
            status: number;
            /** @description Stable machine-readable problem code */
            code: string;
            /** @description Occurrence-specific explanation */
            detail?: string;
            /** @description URI of the request that failed */
            instance?: string;
            /** @description Correlation id (X-Request-Id) */
            requestId?: string;
            /** @description Field-level validation failures */
            errors?: {
              field: string;
              rule: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          username: string;
          password: string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            authenticated: true;
            user: {
              username: string;
            };
          };
        };
      };
      /** @description RFC 9457 Problem Details */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description URI reference identifying the problem type */
            type: string;
            /** @description Short human-readable summary of the problem type */
            title: string;
            /** @description HTTP status code */
            status: number;
            /** @description Stable machine-readable problem code */
            code: string;
            /** @description Occurrence-specific explanation */
            detail?: string;
            /** @description URI of the request that failed */
            instance?: string;
            /** @description Correlation id (X-Request-Id) */
            requestId?: string;
            /** @description Field-level validation failures */
            errors?: {
              field: string;
              rule: string;
              message: string;
            }[];
          };
        };
      };
      /** @description RFC 9457 Problem Details */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description URI reference identifying the problem type */
            type: string;
            /** @description Short human-readable summary of the problem type */
            title: string;
            /** @description HTTP status code */
            status: number;
            /** @description Stable machine-readable problem code */
            code: string;
            /** @description Occurrence-specific explanation */
            detail?: string;
            /** @description URI of the request that failed */
            instance?: string;
            /** @description Correlation id (X-Request-Id) */
            requestId?: string;
            /** @description Field-level validation failures */
            errors?: {
              field: string;
              rule: string;
              message: string;
            }[];
          };
        };
      };
      /** @description RFC 9457 Problem Details */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description URI reference identifying the problem type */
            type: string;
            /** @description Short human-readable summary of the problem type */
            title: string;
            /** @description HTTP status code */
            status: number;
            /** @description Stable machine-readable problem code */
            code: string;
            /** @description Occurrence-specific explanation */
            detail?: string;
            /** @description URI of the request that failed */
            instance?: string;
            /** @description Correlation id (X-Request-Id) */
            requestId?: string;
            /** @description Field-level validation failures */
            errors?: {
              field: string;
              rule: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
}
